version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: test
      MARIADB_USER: admin
      MARIADB_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "13306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
