server:
  port: 8081

spring:
  config:
    import: classpath:secure-yml/oauth2.yml
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:mariadb://localhost:23306/test
    username: admin
    password: 1234
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.spi: DEBUG

jwt:
  secret: a0123456789b0123456789c0123456789d
  refresh-token-validity-seconds: 1209600  # 14일
  access-token-validity-seconds: 3600

