server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:13306/test
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  main:
    web-application-type: reactive

jwt:
  secret: a0123456789b0123456789c0123456789d
  refresh-token-validity-seconds: 1209600  # 14일
  access-token-validity-seconds: 3600

