server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:mariadb://localhost:13306/test
    username: admin
    password: 1234

jwt:
  secret: a0123456789b0123456789c0123456789d
  refresh-token-validity-seconds: 1209600  # 14일
  access-token-validity-seconds: 3600

