server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

jwt:
  secret: a0123456789b0123456789c0123456789d
  refresh-token-validity-seconds: 1209600  # 14일
  access-token-validity-seconds: 3600