server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: user-site-service
          uri: http://localhost:8083
          predicates:
            - Path=/site/{siteId}/**
          filters:
            - StripPrefix=1

        - id: admin-site-service
          uri: http://localhost:8084
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  r2dbc:
    url: r2dbc:mariadb://localhost:23306/test
    username: admin
    password: 1234
jwt:
  secret: a0123456789b0123456789c0123456789d
  refresh-token-validity-seconds: 1209600  # 14일
  access-token-validity-seconds: 3600