version: '3.8'

services:
  config-server:
    build: ../plugins/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ../plugins/config-server/config-repo:/config-repo
    networks:
      - msa-net
  eureka-server:
    build: ../plugins/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - msa-net
  mariadb:
    image: mariadb:latest
    container_name: msa-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: test
      MARIADB_USER: admin
      MARIADB_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "23306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:7.2-alpine
    container_name: msa-redis
    ports:
      - "6379:6379"
    networks:
      - msa-net
        
volumes:
  mariadb_data:

networks:
  msa-net:

